name: Auto Update
on:
  schedule:
    # இது ஒவ்வொரு 30 நிமிடத்திற்கும் ஒருமுறை ஸ்கிரிப்டை இயக்கும்
    - cron: '*/30 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update
        run: |
          pip install requests
          python update.py
      - name: Save
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add playlist.m3u
          git commit -m "Updated" || exit 0
          git push
          
